using PrintMonitor.Native;
using PrintMonitor.Utilities;
using Xunit;

namespace PrintMonitor.Tests;

public class ConfigurationAndDeviceTests : IDisposable
{
    private readonly string _tempDir;

    public ConfigurationAndDeviceTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"printmonitor_cfg_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_tempDir))
            {
                Directory.Delete(_tempDir, true);
            }
        }
        catch { }
    }

    [Fact]
    public void DeviceId_IsGeneratedOnce_And_RemainsConsistentAcrossRestarts()
    {
        var id1 = MachineIdentifier.GetOrCreateDeviceId(_tempDir, null);
        Assert.False(string.IsNullOrWhiteSpace(id1));
        Assert.True(Guid.TryParse(id1, out _));

        // Subsequent call simulating service restart
        var id2 = MachineIdentifier.GetOrCreateDeviceId(_tempDir, null);
        Assert.Equal(id1, id2);
    }

    [Fact]
    public void ConfiguredDeviceId_OverridesAutoGeneratedId()
    {
        var customId = "custom-corporate-device-99";
        var resolved = MachineIdentifier.GetOrCreateDeviceId(_tempDir, customId);
        Assert.Equal(customId, resolved);
    }

    [Fact]
    public void Logger_RedactsSensitiveTokensAndSecrets()
    {
        var rawMessage = "Sending request with api_key: 'secret_abc_123' and bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9";
        var redacted = PrintMonitorFileLogger.RedactSecrets(rawMessage);

        Assert.DoesNotContain("secret_abc_123", redacted);
        Assert.Contains("[REDACTED]", redacted);
    }

    [Fact]
    public void Win32PrintSpooler_StatusMapping_TranslatesFlagsCorrectly()
    {
        // Printing
        var (s1, _) = Win32PrintSpooler.InterpretJobStatus(SpoolerConstants.JOB_STATUS_PRINTING, null, 0, 10);
        Assert.Equal("Printing", s1);

        // Completed
        var (s2, _) = Win32PrintSpooler.InterpretJobStatus(SpoolerConstants.JOB_STATUS_COMPLETE, null, 10, 10);
        Assert.Equal("Completed", s2);

        // Error
        var (s3, err) = Win32PrintSpooler.InterpretJobStatus(SpoolerConstants.JOB_STATUS_ERROR, null, 0, 10);
        Assert.Equal("Error", s3);
        Assert.NotNull(err);

        // Deleting when pages completed
        var (s4, _) = Win32PrintSpooler.InterpretJobStatus(SpoolerConstants.JOB_STATUS_DELETING, null, 5, 5);
        Assert.Equal("Completed", s4);

        // Cancelled
        var (s5, _) = Win32PrintSpooler.InterpretJobStatus(SpoolerConstants.JOB_STATUS_DELETED, null, 0, 5);
        Assert.Equal("Cancelled", s5);
    }
}
