<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <Product>Nexrein Printer Monitor</Product>
    <Company>Nexrein</Company>
    <Description>Nexrein Printer Monitor Control Panel &amp; Manager</Description>
    <Version>2.0.0</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\app.ico" />
    <Resource Include="Resources\app.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrintMonitor\PrintMonitor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.12" />
  </ItemGroup>

</Project>
